baseurl      = "https://0rph3us.github.io"
languageCode = "de-DE"
copyright    = 'Diese Seite ist unter der <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a> lizenziert.'
title        = "Michael im Netz"
theme        = "redlounge"
paginate     = 30
rssuri       = "rss.xml"

[[menu.main]]
    name = "Spickzettel"
    weight = -90
    identifier = "spickzettel"
    url = "/spickzettel/"

[[menu.main]]
    name = "Links"
    weight = -100
    identifier = "links"
    url = "/links/"

[[menu.main]]
    name = "Ãœber mich"
    weight = -110
    identifier = "about"
    url = "/about/"

[[menu.social]]
    pre        = "<i class='fa fa-github'></i>"
    url        = "https://github.com/0rph3us"
    identifier = "github"

[[menu.social]]
    pre        = "<i class='fa fa-rss'></i>"
    url        = "/rss.xml"
    identifier = "rss"


[author]
    name = "Michael Rennecke"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    #post = "/blog/:year/:month/:day/:title/"
    post = "/:section/:year/:month/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[indexes]
    category = "categories"
    tag      = "tags"

[params]
    sidebartitle   = "Michael Rennecke"
    sidebartagline = "Meine Gedanken zu Sicherheit, Linux und Random Stuff"
    highlightStyle = "solarized_light"
    Copyright      = 'Diese Seite ist unter der <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a> lizenziert.'

